#!/bin/bash
set -euo pipefail

cd /usr/src/app

mkdir -p log tmp/pids tmp/files public/assets app/stylesheets/brandable_css_brands
touch app/stylesheets/_brandable_variables_defaults_autogenerated.scss Gemfile.lock log/production.log

bootstrap_file="tmp/.websoft9_bootstrapped"

if [ "${CANVAS_SKIP_BOOTSTRAP:-false}" != "true" ] && [ ! -f "${bootstrap_file}" ]; then
  bundle exec rake db:initial_setup
  touch "${bootstrap_file}"
elif [ "${CANVAS_SKIP_BOOTSTRAP:-false}" != "true" ]; then
  bundle exec rake db:migrate
fi

case "${1:-web}" in
  web)
    exec passenger start --port 80 --environment production --no-friendly-error-pages
    ;;
  jobs)
    exec bundle exec script/delayed_job run
    ;;
  *)
    exec "$@"
    ;;
esac
