version: '3.8'

services:
  rancher:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    privileged: true
    env_file:
      - .env
    ports:
      - "${W9_HTTPS_PORT_SET}:443" # Rancher web console (HTTPS)
    restart: unless-stopped
    volumes:
      - rancher:/var/lib/rancher

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  rancher:
