services:

  mariadb:
    image: mariadb:${W9_DB_VERSION}
    container_name: ${W9_ID}-mariadb
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_log_buffer_size=30M
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

  espocrm:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    env_file: 
      - .env
    volumes:
      - espocrm-data:/var/www/html/data
      - espocrm-custom:/var/www/html/custom
      - espocrm-custom-client:/var/www/html/client/custom
    restart: unless-stopped
    ports:
      - "${W9_HTTP_PORT_SET}:80" # Web Console
    depends_on:
      - mariadb

  # This is need for Cron
  espocrm-daemon:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}-daemon
    env_file:
      - .env
    volumes:
      - espocrm-data:/var/www/html/data
      - espocrm-custom:/var/www/html/custom
      - espocrm-custom-client:/var/www/html/client/custom
    restart: unless-stopped
    entrypoint: docker-daemon.sh
    depends_on:
      - espocrm
          
networks:
  default:
    name: ${W9_NETWORK}
    external: true
      
volumes:
  mariadb:
  espocrm-data:
  espocrm-custom:
  espocrm-custom-client:
