# image: https://hub.docker.com/r/apache/rocketmq
# docs:https://rocketmq.apache.org/docs/quickStart/03quickstartWithDockercompose

version: '3.8'

services:
  namesrv:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}-nameserver
    restart: unless-stopped
    # ports:
    #   - 9876:9876
    command: sh mqnamesrv

  broker:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}-broker
    restart: unless-stopped
    # ports:
      # - 10909:10909
      # - 10911:10911
      # - 10912:10912
    environment:
      - NAMESRV_ADDR=${W9_ID}-nameserver:9876
    depends_on:
      - namesrv
    command: sh mqbroker

  proxy:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    env_file: .env
    depends_on:
      - broker
      - namesrv
    ports:
      - ${W9_PROXY_REMOTING_PORT_SET}:8080
      - ${W9_PROXY_GRPC_PORT_SET}:8081
    restart: unless-stopped
    environment:
      - NAMESRV_ADDR=${W9_ID}-nameserver:9876
    command: sh mqproxy
      
networks:
  default:
    name: ${W9_NETWORK}
    external: true

