services:

  neo4j:
    container_name: ${W9_ID}
    image: ${W9_REPO}:${W9_VERSION}
    env_file: .env
    ports:
      - '${W9_HTTP_PORT_SET}:7474' # Web Console
      - '${W9_DB_PORT_SET}:7687' # Bolt
    restart: unless-stopped
    volumes:
      - neo4j:/data
  
networks:
  default:
    name: ${W9_NETWORK}
    external: true
    
volumes:
  neo4j:
