# Upstream compose reference: https://github.com/apache/superset/blob/6.1.0/docker-compose-non-dev.yml

x-superset-image: &superset-image ${W9_REPO}:${W9_VERSION}
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./src/docker:/app/docker
  - superset_home:/app/superset_home

services:
  redis:
    image: redis:7
    container_name: ${W9_ID}-cache
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    image: postgres:${W9_DB_VERSION}
    container_name: ${W9_ID}-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - EXAMPLES_DB=${EXAMPLES_DB}
      - EXAMPLES_HOST=${EXAMPLES_HOST}
      - EXAMPLES_USER=${EXAMPLES_USER}
      - EXAMPLES_PASSWORD=${EXAMPLES_PASSWORD}
      - EXAMPLES_PORT=5432
    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./src/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  superset:
    env_file: .env
    image: *superset-image
    container_name: ${W9_ID}
    restart: unless-stopped
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    ports:
      - "${W9_HTTP_PORT_SET}:8088" # Web Console
    user: root
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes

  superset-init:
    env_file: .env
    image: *superset-image
    container_name: ${W9_ID}-init
    command: ["/app/docker/docker-init.sh"]
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker:
    env_file: .env
    image: *superset-image
    container_name: ${W9_ID}-worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]

  superset-worker-beat:
    env_file: .env
    image: *superset-image
    container_name: ${W9_ID}-worker-beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    restart: unless-stopped
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

volumes:
  superset_home:
    external: false
  postgresql:
    external: false
  redis:
    external: false

networks:
  default:
    name: ${W9_NETWORK}
    external: true
