services:
  adguardhome:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    ports:
      - "${W9_DNS_TCP_PORT_SET}:53/tcp"      # DNS (TCP)
      - "${W9_DNS_UDP_PORT_SET}:53/udp"      # DNS (UDP)
      - "${W9_HTTP_PORT_SET}:80"             # Web
      - "${W9_DASHBOARD_PORT_SET}:3000/tcp"  # Dashboard

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  adguard-work:
  adguard-conf:
