services:
  seafile:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${W9_HTTP_PORT_SET}:80" # Web Console
    volumes:
      - seafile-data:/shared
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mariadb:${W9_DB_VERSION}
    container_name: ${W9_ID}-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized"
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    container_name: ${W9_ID}-redis
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - exec redis-server --requirepass "$${REDIS_PASSWORD}" --save "" --appendonly no
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  mysql-data:
  seafile-data:
