worker_processes auto;

events {
  worker_connections 1024;
}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen 3080;
    server_name _;

    location / {
      sub_filter_once off;
      sub_filter '</head>' '__DSH_LOCAL_APP_SCRIPT__</head>';
      proxy_pass http://127.0.0.1:3081;
      proxy_http_version 1.1;
      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
      proxy_set_header Accept-Encoding "";
      proxy_set_header Host $http_host;
      proxy_set_header Origin $http_origin;
      proxy_set_header Referer $http_referer;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
  }
}
