services:

  rabbitmq:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    ports:
      - "${W9_ER_PORT_SET}:4369" # Erlang distribution (epmd)
      - "${W9_MQ_PORT_SET}:5672" # AMQP 0-9-1
      - "${W9_HTTP_PORT_SET}:15672" # Management UI
    env_file: .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./src/rabbitmq.conf:/etc/rabbitmq/conf.d/99-websoft9.conf:ro

volumes:
  rabbitmq_data:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
