[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libs"
version = "0.1.0"
description = "CLI for docker-library automation"
requires-python = ">=3.9"
dependencies = [
  "typer>=0.12,<1",
  "rich>=13",
  "requests[socks]>=2",
  "PyYAML>=6",
  "packaging>=24",
  "jsonschema>=4",
  "Jinja2>=3"
]

[project.scripts]
libs = "libs.main:run"

[project.optional-dependencies]
test = [
  "pytest>=8",
]

[tool.setuptools.packages.find]
include = ["libs*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
