services:
  weaviate:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    ports:
      - "${W9_HTTP_PORT_SET}:8080" # HTTP API
      - "${W9_GRPC_PORT_SET}:50051" # gRPC API
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8080/v1/.well-known/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  weaviate_data:
