# image,docs: https://hub.docker.com/r/debezium/server

services:

  debezium:
    image: $W9_REPO:$W9_VERSION
    container_name: $W9_ID
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - $W9_HTTP_PORT_SET:8080
    env_file: .env
    volumes:
      - ./src/application.properties:/debezium/config/application.properties
      - debezium_data:/debezium/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/q/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  debezium_data:


networks:
  default:
    name: $W9_NETWORK
    external: true
