#!/bin/bash

set -a

echo "POSTGRES_USER is set to: '${POSTGRES_USER}'"
echo "POSTGRES_ZAMMAD_PASSWORD is set to: '${POSTGRES_ZAMMAD_PASSWORD}'"
# create zammad user and database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER zammad WITH PASSWORD '${POSTGRES_ZAMMAD_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE zammad TO zammad;
    \c zammad
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO zammad;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO zammad;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO zammad;
EOSQL