services:

  teleport:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    hostname: localhost
    restart: unless-stopped
    entrypoint: ["/usr/bin/dumb-init", "/usr/local/bin/teleport", "start", "-c", "/etc/teleport/teleport.yaml", "--bootstrap=/etc/teleport/bootstrap.yaml"]
    env_file: .env
    ports:
      - "${W9_HTTPS_PORT_SET}:3080" # Teleport Proxy HTTPS (Web UI + API)
      # - "3025:3025" # Auth Service (internal)
      # - "3023:3023" # Node Tunneling (internal)
    volumes:
      - ./src/config:/etc/teleport
      - teleport_data:/var/lib/teleport
    healthcheck:
      test: ["CMD", "/usr/local/bin/tctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  teleport_data:
