services:
  pgadmin:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${W9_HTTP_PORT_SET}:80" # Web Console
    env_file: .env

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  pgadmin:
