services:
  jupyterhub:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    env_file: .env
    ports:
      - "${W9_HTTP_PORT_SET}:8000" # Web Console
    volumes:
      - jupyterhub:/srv/jupyterhub
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/jupyterhub_config.py:/etc/jupyterhub/jupyterhub_config.py
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
          python -c "import jupyterlab" >/dev/null 2>&1 || pip install jupyterlab
          if ! getent passwd "$${USERNAME}" >/dev/null; then
            useradd "$${USERNAME}" -m
            echo "$${USERNAME}:$${PASSWORD}" | chpasswd
          fi
          jupyterhub upgrade-db -f /etc/jupyterhub/jupyterhub_config.py
          exec jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
    environment:
      USERNAME: ${W9_LOGIN_USER}
      PASSWORD: ${W9_POWER_PASSWORD}


networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  jupyterhub:
