services:
  mongo:
    image: ${W9_REPO}:${W9_VERSION}
    restart: unless-stopped
    container_name: ${W9_ID}
    ports:
      - "${W9_DB_PORT_SET}:27017" # MongoDB
    env_file: .env
    command: --wiredTigerCacheSizeGB 2 --config /etc/mongod.conf
    volumes:
      - mongo_data:/data/db
      - ./src/mongod.conf:/etc/mongod.conf

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  mongo_data:
