services:

  checkmate:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    stop_grace_period: 60s
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "${W9_HTTP_PORT_SET}:52345" # Web Console
    env_file: .env
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:52346/livez',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))",
        ]
      interval: 15s
      timeout: 3s
      start_period: 60s
      start_interval: 2s
      retries: 3

  mongodb:
    image: mongo:${W9_DB_VERSION}
    container_name: ${W9_ID}-mongodb
    restart: unless-stopped
    command: ["mongod", "--quiet", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'${W9_ID}-mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

volumes:
  mongo_data:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
