services:
  onlyofficedocs:
    container_name: ${W9_ID}
    image: ${W9_REPO}:${W9_VERSION}
    restart: unless-stopped
    env_file:
      - .env
    cpu_percent: 50
    ports:
      - "${W9_HTTP_PORT_SET}:80" # Web Console
    expose:
      - '80'
      - '443'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/info/info.json"]
      interval: 30s
      retries: 5
      start_period: 60s
      timeout: 10s
    volumes:
      - data:/var/www/onlyoffice/Data
      - log:/var/log/onlyoffice
      - lib:/var/lib/onlyoffice
      - fonts:/usr/share/fonts/truetype/custom
      - forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  data:
  log:
  lib:
  fonts:
  forgotten:
