services:
  portainer:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    ports:
      - "${W9_HTTP_PORT_SET}:9000" # Portainer web UI and REST API
    env_file: .env
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  portainer:
