# Loaded only when the Spring "postgres" profile is active.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://springboot-postgresql:5432/springboot}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:springboot}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=5000
