version: '3.8'

services:
  redmine:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    ports:
      - "${W9_HTTP_PORT_SET}:3000" # Redmine web console
    volumes:
      - redmine_files:/usr/src/redmine/files
      - ./src/configuration.yml:/usr/src/redmine/config/configuration.yml
    env_file: .env
    environment:
      REDMINE_DB_MYSQL: ${REDMINE_DB_MYSQL}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_PLUGINS_MIGRATE: ${REDMINE_PLUGINS_MIGRATE}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - mysql

  mysql:
    image: mysql:${W9_DB_VERSION}
    container_name: ${W9_ID}-mysql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${W9_POWER_PASSWORD}
      MYSQL_DATABASE: ${W9_ID}
      MYSQL_USER: ${W9_ID}
      MYSQL_PASSWORD: ${W9_POWER_PASSWORD}

volumes:
  mysql:
  redmine_files:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
