services:

  app:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    ports:
      - "${W9_HTTP_PORT_SET}:8080" # Web UI
    env_file: .env
    volumes:
      - open-webui:/app/backend/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8080/health | jq -ne 'input.status == true' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  ollama:
    image: ollama/ollama:0.13.1
    container_name: ${W9_ID}-ollama
    restart: unless-stopped
    profiles:
      - ollama
    volumes:
      - ollama:/root/.ollama

  chroma:
    image: chromadb/chroma:1.5.9
    container_name: ${W9_ID}-chroma
    restart: unless-stopped
    profiles:
      - chroma
    volumes:
      - chroma:/data

volumes:
  open-webui:
  ollama:
  chroma:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
