services:
  app:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    shm_size: "2g"
    ports:
      - "${W9_HTTP_PORT_SET}:4444" # Selenium WebDriver API
      - "${W9_ADMIN_PORT_SET}:7900" # noVNC admin console
    env_file: .env

networks:
  default:
    name: ${W9_NETWORK}
    external: true
