services:

  moodle:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${W9_HTTP_PORT_SET}:80" # Web Console
    volumes:
      - moodle_html:/var/www/html
      - moodle_data:/var/moodledata
      - ./src/php.ini:/usr/local/etc/php/conf.d/zz-websoft9.ini:ro
      - ./src/disable-sslproxy.sh:/docker-entrypoint.d/25-disable-sslproxy.sh:ro
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1/login/index.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

  mariadb:
    image: mariadb:${W9_DB_VERSION}
    container_name: ${W9_ID}-mariadb
    restart: unless-stopped
    env_file: .env
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=512M
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  moodle_html:
  moodle_data:
  mariadb_data:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
