# image: https://hub.docker.com/r/websoft9dev/moodle (self-built, base: moodlehq/moodle-php-apache)
# docs: https://docs.moodle.org/en/Installation_quick_guide

services:
  moodle:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${W9_HTTP_PORT_SET}:${W9_HTTP_PORT}"
    volumes:
      - moodle_app:/var/www/html
      - moodle_data:/var/moodledata
      - ./src/php.ini:/usr/local/etc/php/conf.d/moodle.ini
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:${W9_DB_VERSION}
    container_name: ${W9_ID}-mariadb
    restart: unless-stopped
    env_file: .env
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=512M
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  moodle_app:
  moodle_data:
  mariadb_data:


networks:
  default:
    name: ${W9_NETWORK}
    external: true
