services:

  prometheus:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./src/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    ports:
      - "${W9_HTTP_PORT_SET}:9090" # Web Console

  prometheus-pushgateway:
    image: prom/pushgateway:v1.11.3
    container_name: ${W9_ID}-pushgateway
    restart: unless-stopped

  prometheus-alertmanager:
    image: prom/alertmanager:v0.34.0
    container_name: ${W9_ID}-alertmanager
    restart: unless-stopped
    volumes:
      - alertmanager:/alertmanager

volumes:
  prometheus:
  alertmanager:

networks:
  default:
    name: ${W9_NETWORK}
    external: true
