services:
  varnish:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    restart: unless-stopped
    ports:
      - "${W9_HTTP_PORT_SET}:80" # Web
    volumes:
      - ./src/default.vcl:/etc/varnish/default.vcl:ro
    env_file: .env
    tmpfs:
      - /var/lib/varnish/varnishd:exec

networks:
  default:
    name: ${W9_NETWORK}
    external: true
