; Moodle recommended PHP settings
; Edit this file and restart the container to apply changes

memory_limit = 512M
upload_max_filesize = 512M
post_max_size = 512M
max_execution_time = 600
max_input_vars = 5000
max_input_time = 600
