services:
  app:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    extra_hosts:
      host.docker.internal: host-gateway
    restart: unless-stopped
    ports:
      - "${W9_HTTP_PORT_SET}:8000" # Web Console
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - openhands-home:/home/openhands/.openhands
      - openhands-projects:/projects


volumes:
  openhands-home:
  openhands-projects:
    
networks:
  default:
    name: ${W9_NETWORK}
    external: true
