services:
  vault:
    image: ${W9_REPO}:${W9_VERSION}
    container_name: ${W9_ID}
    cap_add:
      - IPC_LOCK
    ports:
      - "${W9_HTTP_PORT_SET}:8200" # Vault UI and HTTP API and CLI
    env_file:
      - .env
    volumes:
      - vault-logs:/vault/logs
      - vault-file:/vault/file
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8200/v1/sys/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: ${W9_NETWORK}
    external: true

volumes:
  vault-logs:
  vault-file:
